package com.facilitalab.models;

public enum EstadoEnum {
AGUARDANDO_TRIAGEM,
AGUARDANDO_INFORMACOES,
AGUARDANDO_APROVACAO_DESIGN,
EM_ANALISE,
EM_MODELAGEM,
EM_CORRECAO,
USINAGEM,
FINALIZADO,
CANCELADO
}
